# Generated by Django 2.2.2 on 2019-06-11 22:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(max_length=100, unique=True)),
                ('sub_title', models.CharField(max_length=100, unique=True)),
                ('stamp', models.TextField(max_length=80)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imagefile', models.ImageField(blank=True, null=True, upload_to='static/media/flyers/', verbose_name='')),
                ('alternate_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_link', models.CharField(max_length=500)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/media/icons/', verbose_name='')),
            ],
        ),
    ]
